### ISSUE TITLE
Create test plan for rubric

### ISSUE THREAD

**Issue by amyashida** [18F/cms-oversight#16]
**Who is the user?** 
18F, Nick + Liz

**What will this help them do?** 
Understand scope of testing and identify materials needed 

**When is it needed?** 
5/14

**What steps are needed to make it a reality?** 
- [x] draft test plan for round 1
- [x] collect feedback from CMS
- [x] map out what we envision the level of engagement on a pilot to look like

**Comment by alexpandel** [comment]
@amyashida FYI, working on this [in this doc](https://docs.google.com/document/d/1ur27xADwaznF3NktOQHxjxVw51COIBVnpeuC90bSSKs/edit#); I was thinking of cleaning this up a little when I sign back on Mon morning and maybe getting some of the steps we spelled out into our backlog, but feel free to get in there as well if you feel inspired!

**Comment by alexpandel** [comment]
@amyashida after we prioritize/refine the new cards that relate to this w/ Nick & Liz tomorrow, we can probably close this one!
