### ISSUE TITLE
Get feedback on rubric from 18F colleagues

### ISSUE THREAD

**Issue by alexpandel** [18F/cms-oversight#20]
**Who is the user?** 
18F team, SOs

**What will this help them do?**
Input and feedback from the broader 18F team will help ensure the rubric benefits from the breadth of the 18F team's skills & expertise

**When is it needed?**
Before we begin piloting

**What steps are needed to make it a reality?**
- [x] get first draft of rubric (#3) to a shareable state
- [x] decide how we want to collect feedback
- [x] schedule procurement feedback
- [x] schedule engineering feedback
- [x] decide when/how we'll synthesize (& create issues for any next steps)

**Comment by alexpandel** [comment]
**Areas where we want feedback:**
- “Using modern software dev practices”
- “Using modern procurement practices”

**Questions about each area:**
- Are the things we pulled out the most critical things? What’s missing? What feels not that important?
- If you had to single out the top ~5 things that would have the most impact on success, what would they be?

**From whom:**
- First: Procurement folks
- Second: Dev folks

**How we'll gather it:**
- Give folks time to review the thing in advance with our questions in mind
- Then an hour session to discuss their feedback

**Comment by amyashida** [comment]
We started collecting feedback this week.

**Comment by alexpandel** [comment]
spun up #32 to capture next steps coming out of this!
