### ISSUE TITLE
Decide whether/how to involve MITRE on pilots

### ISSUE THREAD

**Issue by alexpandel** [18F/cms-oversight#22]
**Who is the user?** 
18F team; CMS

**What will this help them do?**
Have clarity on how to relate our work to other teams

**When is it needed?**
Before pilots begin

**What steps are needed to make it a reality?**
- [ ] discuss with Nick & Liz
- [ ] decide on the best path forward

**Comment by amyashida** [comment]
18F could add a few folks from MITRE to the shipmail update to keep informed

Nick & Liz could help triage when to refer between each group
