### ISSUE TITLE
Get Amy & Alex access to CMS's internal wiki

### ISSUE THREAD

**Issue by alexpandel** [18F/cms-oversight#27]
**Who is the user?** 
18F team; SOs 

**What will this help them do?** 
learn about existing setup of wiki, so that we can structure how our work gets delivered to state officers to be as user-friendly as possible and optimize for successful onboarding & adoption

**When is it needed?** 
Not for a month or two, but we want to start the process now!

**What steps are needed to make it a reality?** 

- [ ] Liz or Nick look into what it will take to start the access process, and let Amy & Alex know what they need to do
- [ ] update this card with next steps as we learn them

**Comment by nickarrow** [comment]
Let's talk. To make this happen we need a week or two of credentialing, a Cisco VPN client on your computers, and a few more annual requirements. 

Alternatively, we could just build a wiki page here, and I can copy/pasta it over to our internal Wiki (or some sort of workaround like that).

**Comment by alexpandel** [comment]
👍  sounds good, let's discuss! fwiw, our current take is it'll be really important eventually that we have the ability to at least see and navigate around the existing wiki to understand how best to structure our content to ensure it makes sense and is usable within that context. And since we don't need the access ASAP, we figure getting started jumping through the right hoops now so we have the access when we need it later is well worth the effort!
