### ISSUE TITLE
Define coordination OKRs and how 18F can help with that workstream

### ISSUE THREAD

**Issue by amyashida** [18F/cms-oversight#29]
**Who is the user?**
The coordination team, SOs, states

**What will this help them do?**
Coordinating communications to SOs and states will help ensure continuity of message, avoid overwhelming users, and increase coordination among the teams. 

**When is it needed?**
This week

**What steps are needed to make it a reality?**
- [ ] work with Liz to define OKRs
- [ ] outline how 18F can help support the OKRs

**Comment by alexpandel** [comment]
closing this issue in favor of [its duplicate](https://github.com/CMSgov/CMCS-DSG-DSS-Oversight/issues/4) in the new shared CMS repo.
