### ISSUE TITLE
Set up 18F "advisory board" to inform our work

### ISSUE THREAD

**Issue by alexpandel** [18F/cms-oversight#35]
**Who is the user?** 
18F team; CMS

**What will this help them do?**
more regularly draw upon the diverse expertise across the 18F team from feedback and input into our work, to ensure our work can benefit from as many perspectives as possible. 

**When is it needed?**
no real urgency, but we know it could have immediate benefit once it exists

**What steps are needed to make it a reality?**
- [x] figure out what's the lightest-weight way to establish and maintain this (could other at 18F help set it up/run it?)
- [ ] get it started!

**Comment by amyashida** [comment]
outlined what this could look like here: 
https://docs.google.com/document/d/1dYUhUh6OZwRAJPdzz-yw8202r042C9w-7isHfW5Kh5E/edit?usp=chrome_omnibox&ouid=106439708843062323379

**Comment by alexpandel** [comment]
closing this issue in favor of [its duplicate](https://github.com/CMSgov/CMCS-DSG-DSS-Oversight/issues/3) in the new shared CMS repo.
